'\" t
.\"     Title: blockade
.\"    Author: Michael L. Schaecher
.\"  Homepage: <https://github.com/mschaecher78/blockade/>
.\"      Date: 01\ \&july\ \&2020
.\"    Manual: blockade
.\"    Source: blockade 0.9.5.0
.\"  Language: English
.\"
.TH "BLOCKADE" "1" "09\ \&June\ \&2020"
.\"
.SH "NAME"
.PP
Blockade \- Update /etc/hosts file using Steven Black hosts project https://github.com/StevenBlack/hosts.
.SH SYNOPSIS
.PP
blockade [ options ] [ options ]=date
.SH DESCRIPTION
.PP
\fBblockade\fR,
enables you to apply commonly know url's and websites that bad for you and your computer to the /etc/hosts
file. The file is automaticaly updated on the backend with you having to worry.
.PP
.TP
\fB--edit=\fR
Add url or website to the hosts file; example \fB--edit=www.badwebiste.com\fR.
.TP
\fB--update\fR
Manually update hosts using the current configurations. This option is ran automaticaly by systemd timer service.
.TP
\fB--interval=date\fR
Set the time when to update the hosts file. This can be daily, weekly, monthly or yearly; you can also set pick a
specific date and time when this is done (example day-month-year-hour:minute), the default is monthly. See \fBSET
INTERVAL\fR for more details.
.TP
\fB--type\fR
Show's a list of avialible hosts to download and install, the default is unified. See \fBHOSTS TYPE\fR for more details.
.TP
\fB--info\fR
Displays info according to systemctl.
.TP
\fB--help\fR
Displays blockade help info.
.TP
\fB--version\fR
Display blockade version.
.PP
.SH SET INTERVAL
By defaul the hosts file is updated monthly, but this can be changed manually by running the command/'s below.
.PP
\fB	blockade --interval=[daily][weekly][monthly][yearly][year-month-day hour:minute:second]
.PP
To set a specific time use 24hr UTC. Example \fB2020-07-04 00:00:00\fR = update /etc/host on July 04, 2020 @ midnight.
An "\fB*\fR" can be used to as a wildcard like so: \fB*-*-04 00:00:00\fR will cause /etc/hosts to be updated once a month
on the fourth @ midnight.
.SH HOSTS TYPE
.PP
There are a number of hosts file configurations made avialible by Steven Black. Visit his github page and feed the project
@ \fBhttps://github.com/StevenBlack/hosts\fR. While the default is the \fBunified\fR this can eazily be changed by running
\fB--type\fR.
.PP
Default = \fBUnified\fR
.SH ALSO SEE
.PP
\fBhostname(1)\fR,
\fBresolver(3)\fR,
\fBhost.conf(5)\fR,
\fBresolv.conf(5)\fR,
\fBhostname(7)\fR,
\fBnamed(8)\fR,
\fBresolv.conf(5)\fR.
