#!/bin/bash

set -e



# If blockade is alread installed.
if [ -f /usr/lib/blockade/blockade.conf ] ; then
	echo "detected blockade.conf ..... backing up"
	mv -f ${LIB}/blockade.conf ${LIB}/blockade.conf.old
fi

echo "installing:  ${APP}/blockade"		# Feed back is a good thing.
if ! sed "246iVERSION=\"${VERSION}\"" scr/blockade > ${APP}/blockade ; then
	echo "Error: failed to install ${APP}/blockade"
	exit 1
fi

echo "installing: ${SERVICE}/blockade-hosts-update.timer
installing: ${SERVICE}/blockade-hosts-update.service"
if ! cp -f scr/blockade-hosts-update.* ${SERVICE}/ > /dev/null ; then
	echo "Error: failed to install ${SERVICE}/blockade-hosts-update.timer"
	echo "Error: failed to install ${SERVICE}/blockade-hosts-update.service"
	exit 1
else
	echo "installing: ${BLOCKADE}/type-info"
	if ! cp -f scr/doc/type-info ${BLOCKADE}/type-info ; then
		echo "Error: failed to install ${BLOCKADE}/type-info"
	fi

	echo "installing: ${LIB}/blockade.conf"
	if ! cp -f scr/blockade.conf ${LIB}/blockade.conf ; then
		echo "Error: failed to install  ${LIB}/blockade.conf"
	fi

	cp -vf man/blockade.1 ${TMP}/${MAN}/blockade.1

	if ! gzip -9 -vf ${TMP}/${MAN}/blockade.1 ; then
		echo "Error" && exit 1
	fi

	# Copy and conpress changelog.
	if ! cp -vf changelog copyright ${DOC}/ ; then
		echo "Missing: ${DOC} && ${SERVICE}" && exit 1
	else

		if ! gzip -9 -vf ${DOC}/changelog ; then
			echo "Error" && exit 1
		fi

	fi

fi

echo "restoring configuration"
mv -f /usr/lib/blockade/blockade.conf.old /usr/lib/blockade/blockade.conf

echo "fixing premissions"
chmod 0755 ${APP}/blockade
chown -R root:root /usr/bin/blockade /usr/lib/blockade \
	/lib/systemd/system/blockade-hosts-update.* \
	/usr/share/doc/blockade

if which systemctl >/dev/null 2>&1 ; then
	systemctl enable blockade-hosts-update.timer || true
fi
