#!/bin/bash
#
# Determ which hosts file to download.

set -e

# Create package directories.
if ! mkdir -vp ${DEBIAN} ${SERVICE} ${APP} ${DOC} ; then
	echo "Error: unable to create directories"
elif mkdir -vp ${DEBIAN} ${SERVICE} ${APP} ${DOC} ; then

	if ! cp -vf scr/blockade-monthly.* ${SERVICE}/ ; then
		echo "Error: missing" && exit 1
	fi

	if ! cp -vf changelog copyright ${DOC}/ ; then
		echo "Missing: ${DOC} && ${SERVICE}" && exit 1
	else
		if ! gzip -9 -vf debian/tmp/usr/share/doc/blockade/changelog ; then
			echo "Error" && exit 1
		fi
	fi

	if ! cp -vf scr/postinst ${DEBIAN}/postinst ; then
		echo "Missing: installer" && exit 1
	fi

scripts/make-blockade

fi
