#!/bin/bash

set -e

chmod a+x -v debian/tmp/usr/bin/blockade debian/tmp/DEBIAN/postinst

size_lib=$(du -s debian/tmp/lib/ | awk -F' ' '{print $1}')
size_usr=$(du -s debian/tmp/usr/ | awk -F' ' '{print $1}')

let total=${size_lib}+${size_usr}

# Create the control file
cat <<EOF > debian/tmp/DEBIAN/control
Package:${NAME}
Version: ${VERSION}
Architecture: all
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Installed-Size: ${total}
Depends: wget, systemd
Section: net
Priority: optional
Description: Update hosts
 Using Steven Black's' github hosts project. This enables
 the hosts to be used to manage security while surffing the web.
EOF

if ! md5sum ${SERVICE}/* ${DOC}/* ${APP}/* > $DEBIAN/md5sums ; then
	echo "Error: md5sum"
fi

if ! dpkg-deb --build debian/tmp ../blockade_${VERSION}_all.deb ; then
	echo "Package not built!"
fi
