#!/bin/bash

set -e

# Create the main script for Blockade.
cat <<EOF > debian/tmp/usr/bin/blockade
#!/bin/bash

# Blockade; a program that updates the hosts file automaticaly.
# Copyright (C) 2020  Michael L. Schaecher

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

set -e

# Since the link is long it makes sense to shorten it to veriable.
download_link="${LINK}"

new_hosts () {

# Recreate the header for the hosts file
cat <<EOF > /etc/hosts
# Blackade generated hosts on \`date -R\` on \`hostname\`
#
# This hosts file is updated weekly and is sourced from Steven Black hosts.
# github page.If you come accross any links that you feel should be
# add, feel free to contact me or Mr. Black on github.
#
# https://github.com/mschaecher78/blockade/issues
# or
# https://github.com/StevenBlack/hosts/issues
#
# localhost @ 127.0.0.1
# redirect  @ 0.0.0.0
#

127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
::1 localhost
::1 ip6-localhost
::1 ip6-loopback
fe80::1%lo0 localhost
ff00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
0.0.0.0 0.0.0.0

# ==================================================
EOF

echo "EOF" >> debian/tmp/usr/bin/blockade

cat <<EOF >> debian/tmp/usr/bin/blockade

}

export -f new_hosts

HELP="
Useage = blockade [option]

	Options
	    update-hosts         Download and update hosts file (must be root).
	    help                 Display this help dialog.

GPL v2 copyright (2020) Michael L. Schaecher
"

case \$1 in
	update-hosts)

		# Only run if the user is root.
		if [ "\${EUID}" -ne 0 ] ; then
			echo "Error: must be root user!"
		elif [ "\${EUID}" -ne 1 ] ; then
			echo "downloading \${download_link}" && sleep 0.5

			# Download and copy only what is maked by website links,
			# egnoring the header of the file.
			if ! wget -O - -cq \${download_link} |
			   awk 'NR < 40{next}1' | grep '0.0.0.0' >> /tmp/hosts ; then
				echo "Error: unable to update hosts" && exit 1
			fi

			echo "Building new hosts file" && sleep 0.5 && new_hosts

			# Just incase something happened.
			if ! ls /tmp | grep hosts > /dev/null ; then
				echo "Error: unable to create new hosts files" && exit 1
			fi

			sleep 0.5

			if ! cat /tmp/hosts > /etc/hosts ; then
				echo "Error: unable to install /etc/hosts" && exit 1
			fi

			rm -f /tmp/hosts && echo "restarting NetworkManager.service"
			systemctl restart NetworkManager.service
			sleep 7 && echo "Finished :)"
		fi
	;;
	help)
		echo "\${HELP}" && exit 0
	;;
	*)
		echo "Error: Unknow option!" &&exit 1
	;;

esac

EOF
