#!/bin/bash
#
# Determ which hosts file to download.

set -e

mkdir -vp ${TMP}/${DEBIAN} ${TMP}/${SERVICE} ${TMP}/${APP} \
	${TMP}/${DOC} ${TMP}/${BLOCKADE} ${TMP}/${LIB}

CHANGELOG=$(cat changelog)

COMMIT=$(cat .git/COMMIT_EDITMSG)

ROOT=$(pwd)

# Make sure that the commit message is not dupicated in then
# changelog.
if grep "* ${COMMIT}" changelog > /dev/null ; then
	cp changelog debian/changelog
else
cat <<EOF > debian/changelog
${NAME_VERSION} (${VERSION}) ubuntu; urgency=medium

  * ${COMMIT}

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

${CHANGELOG}
EOF
fi

cp -f debian/changelog changelog

# Aviod using cp to copy the main script because the version needs
# to be set.
sed "247iVERSION=\"${VERSION}\"" scr/blockade > ${TMP}/${APP}/blockade

if ! cp -vf scr/blockade-hosts-update.* ${TMP}/${SERVICE}/ ; then
	echo "Error: missing" && exit 1
else
	cp -vf scr/doc/* ${TMP}/${BLOCKADE}/
	cp -vf scr/blockade.conf ${TMP}/${LIB}/blockade.conf

	# Copy and conpress changelog.
	if ! cp -vf debian/changelog copyright ${TMP}/${DOC}/ ; then
		echo "Missing: ${TMP}/${DOC} && ${TMP}/${SERVICE}" && exit 1
	else
		if ! gzip -9 -vf ${TMP}/${DOC}/changelog ; then
			echo "Error" && exit 1
		fi
	fi

	if ! cp -vf scr/postinst ${TMP}/${DEBIAN}/postinst ; then
		echo "Missing: installer" && exit 1
	else
		chmod -R a+rX "${TMP}"
		chmod 0755 ${TMP}/${DEBIAN}/postinst ${TMP}/${APP}/blockade \
			${TMP}/${LIB}/blockade.conf
	fi

fi

# Generate a control file
cat <<EOF > debian/control
Source: ${NAME_VERSION}
Section: networking
Priority: optional
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: cp, gzip, wget, dpkg
Homepage: https://www.github.com/mschaecher78/blockade/

Package:${NAME}
Architecture: all
Depends: wget, systemd
Description: Update hosts
 Using Steven Black's' github hosts project. This enables
 the hosts to be used to manage security while surffing the web.
EOF

cd ${TMP}

find . -type f ! -path './DEBIAN/*' -printf '%P\0' | xargs -r0 md5sum > DEBIAN/md5sums

cd ${ROOT}

if dpkg-gencontrol -p${NAME} -P"${TMP}" ; then
	dpkg-deb --build ${TMP} ..
fi
